### ISSUE TITLE
Support for nested container directives

### ISSUE THREAD

**Issue by enagy27** [bent10/marked-extensions#110]
- Extension Name: marked-directive
- Extension Version: 1.0.5

### Use case
I'm trying to parse the following markdown:
```md
:::carousel

::::carousel-slide
Title
Description

![Image](/image.jpg)
::::

:::
```

This is something that's proposed by the directive spec but I can't seem to get this to work currently.

### Proposal
I think the best way to have it be supported would be to add a `$` to the end of the result of `getDirectivePattern` for container level directives.

This solution would still mean having to explicitly declare separate markers for each level of nesting, but it should make it possible to nest.

**Comment by enagy27** [comment]
I may actually have misread the spec? It looks like other implementations expect that the outer elements have more colons than the inner elements, which would work with the current implementation:

```md
::::carousel

:::carousel-slide
Title
Description

![Image](/image.jpg)
:::

::::
```

This would make sense with the greediness of regular expressions. If that's the case, perhaps this would just be best as a documentation update pointing to another implementation such as [micromark-extension-directive](https://github.com/micromark/micromark-extension-directive?tab=readme-ov-file#syntax).

**Comment by bent10** [comment]
Thanks for bringing this up!

You're right—the directive spec supports nesting by using more colons for the outer container. Your second example with 4 colons for `carousel` and 3 colons for `carousel-slide` is the correct approach.

Alternatively, you can also use different markers for each level. For example, the `.container` uses colons (`:::`), and the `.item` uses plus signs (`+++`):

````md
:::{.container}

+++{.item}

### Title

Content ![Image](/image.jpg), with code:

```python
num1 = 5
num2 = 3
sum = num1 + num2
print(f"The sum of {num1} and {num2} is {sum}")
```

+++

:::
````

I will update the documentation with examples to clarify this nesting behavior.

Sorry for the delay! I’ve been struggling to find time to review it.

**Comment by enagy27** [comment]
Not at all! Thank you for clarifying that and for updating the docs 🙏
