### ISSUE TITLE
Reference-style links don't work in alerts

### ISSUE THREAD

**Issue by benhatsor** [bent10/marked-extensions#120]
- Extension Name: marked-alert
- Extension Version: 2.0.2
- Project Version: N/A
- Device: [e.g Desktop] N/A
- OS@version (or Browser): N/A
- Node And NPM Version: N/A

### Description

Reference-style links ([documentation](https://spec.commonmark.org/0.31.2/#reference-link)) don't work in the marked-alert GFM alerts, while they do work on GitHub (see below).
[See here for examples of reference-style links.](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links)

**To Reproduce** _(⚠️ read below)_

### Expected Behavior

Input Markdown:
```
> [!NOTE]
> [Reference-style link][1]

> [!NOTE]
> [Another reference-style link]

[1]: https://google.com
[Another reference-style link]: https://github.com
```

Output:
> [!NOTE]
> [Reference-style link][1]

> [!NOTE]
> [Another reference-style link]

[1]: https://google.com
[Another reference-style link]: https://github.com

### Actual Behavior

Output:
<img width="237" alt="Screenshot 2024-09-25 at 4 19 07 PM" src="https://github.com/user-attachments/assets/7b32bf64-7aca-44d5-acc0-911268a71a7b">
[Codepen](https://codepen.io/benhatsor/pen/QWewMRm)

**Comment by bent10** [comment]
Hi @benhatsor,

I’ve just resolved the issue in the latest release. Please update and check if it's working now.

**Comment by benhatsor** [comment]
The reference-style links in alerts work now, but it seems to have broken the alert rendering:

For this Markdown (from [GitHub's example](https://github.com/orgs/community/discussions/16925)):

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.
```

The library renders this:
<img width="549" alt="Screenshot 2024-10-07 at 3 06 35 PM" src="https://github.com/user-attachments/assets/fa2bf3ef-9ec3-44ba-88a4-7563b4b15e11">

While GitHub renders this:
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

[Codepen](https://codepen.io/benhatsor/pen/gOVMVaX)

**Comment by benhatsor** [comment]
Hey, thanks! The previous issue's been fixed, but it seems to have created another issue:

For this Markdown:
```
> [!NOTE]
> Line 1 (note the two extra spaces at the end)  
> Line 2  
> Line 3
```

The library renders this:
<img width="427" alt="Screenshot 2024-10-30 at 10 48 20 PM" src="https://github.com/user-attachments/assets/bed5458b-5dff-4fc7-983e-bcabf84f7c4c">

While GitHub renders this:
> [!NOTE]
> Line 1 (note the two extra spaces at the end)  
> Line 2  
> Line 3

[CodePen](https://codepen.io/benhatsor/pen/GRVdWLW)

**Comment by bent10** [comment]
It looks like the issue arises from how `marked` handles line breaks within blockquote sections. Since `marked-alert` only transforms blockquote tokens to alert tokens, the line breaks are processed differently, which results in the discrepancy you're seeing between the library’s output and GitHub’s rendering.

One workaround is to use the following method, which replaces line breaks within the alert with `<br>` tags. Here’s how it looks:

```javascript
new marked.Marked()
  .use(
    // Define this extension before 'marked-alert'
    {
      walkTokens({ type, tokens }) {
        if (type === "alert") {
          tokens.forEach(token => {
            if (token.type === "paragraph") {
              marked.walkTokens(token.tokens, tok => {
                if (tok.type === "text") {
                  tok.text = tok.text.replace(/\n+/g, "<br>")
                }
              })
            }
          })
        }
      }
    },
    markedAlert()
  )
  .parse(md)
```

> [!CAUTION]
> This approach might have side effects if other extensions rely on similar transformations, so it’s best to test thoroughly.

Since this behavior may affect other users handling line breaks in blockquotes with custom extensions, you might want to consider submitting a proposal in the `marked` repository to support this functionality natively.

**Comment by bent10** [comment]
@benhatsor, You can ignore my previous response! 
I missed the hard line breaks in your example due to an auto-trim setting in my editor. 

This will be resolved in the next release!

**Comment by benhatsor** [comment]
It still doesn't render properly :( This is how the library renders it (as seen in the [CodePen](https://codepen.io/benhatsor/pen/GRVdWLW)):
<img width="389" alt="Screenshot 2024-11-30 at 7 01 16 PM" src="https://github.com/user-attachments/assets/8ba28f16-815a-4555-aad5-8cd1a77a2e11">

And this is how GitHub renders it:
> [!NOTE]
> Line 1 (note the two extra spaces at the end)  
> Line 2  
> Line 3

Markdown (the same as before):
```
> [!NOTE]
> Line 1 (note the two extra spaces at the end)  
> Line 2  
> Line 3
```
