### ISSUE TITLE
Lexer don't use the extensions ?

### ISSUE THREAD

**Issue by mathieunicolas** [bent10/marked-extensions#132]
- Extension Name: markedAlert
- Extension Version: latest
- Project Version: latest
- Device: Desktop
- OS@version (or Browser): macOS@latest, firefox@132.0b8 (aarch64)
- Node And NPM Version: node@18.20.4, pnpm@9.12.1

### Description

Hello there,

I basically need to use the lexer, then the parser. My code looks like this : 

```ts
import { Marked } from 'marked'
import markedAlert from 'marked-alert'

const marked = new Marked()
marked.use(markedAlert())
```

Later in the code, I use these functions : 
```ts
marked.lexer(markdown)

// elsewhere
marked.parser(tokens)
```

The markedAlert extension is not used, and alerts just look like a blockquote. I don't think it's a bug, I think it's more something I don't understand with how marked works. I've read the doc and unfortunately all the things I've tried didn't work.

If I use `marked.parse(markdown)`, the alert is rendered.
**To Reproduce** _(⚠️ read below)_

https://stackblitz.com/edit/github-j7rreh?file=app.vue

It's a nuxt app, there's an `app.vue` file with the JS and the HTML for rendering.

Thanks !!

**Comment by bent10** [comment]
Hi @mathieunicolas,

Thanks for providing the code and details!

It looks like `markedAlert` isn’t applying because the `lexer` and `parser` methods don't automatically integrate all extension settings when used separately. `marked.parse(markdown)` works because it applies both the lexer and parser steps, using the extensions together by default. Here’s how to manually integrate `markedAlert` in this context:

```typescript
import { Marked } from 'marked'
import markedAlert from 'marked-alert'

const marked = new Marked()
const tokens = marked.lexer(markdown)

// Get the walkTokens function and extensions from markedAlert
const { walkTokens, extensions } = markedAlert()

// Convert 'blockquote' tokens to 'alert' tokens
marked.walkTokens(tokens, walkTokens)

// Configure parser options to recognize alert tokens
const parserOptions = {
  extensions: {
    renderers: extensions.reduce((acc, { name, renderer }) => {
      acc[name] = renderer
      return acc
    }, {}),
  },
}

// Now parse the tokens with the custom options
const html = marked.parser(tokens, parserOptions)

console.log(html)
```

Let me know if this resolves the issue!

**Comment by mathieunicolas** [comment]
Hi @bent10, thank you very much ! 
It definitely resolves the issue ! Is it something that occurs with all extensions, or is it something related to markedAlert ?

Do you think it should be covered in the marked doc ?

Thanks again !

**Comment by bent10** [comment]
You're welcome, @mathieunicolas!

Yup, this kind of issue can arise with other extensions as well, especially those that rely on both lexer and parser transformations (like `marked-alert`). When extensions don’t automatically apply across all methods, manual integration, like we did here, becomes necessary.

As for the documentation, this would indeed be a valuable addition! Many users rely on `marked`’s modular methods (`lexer` and `parser`), so it would help to clarify how extensions interact with each of these functions separately. You might consider opening an issue or PR in the `marked` repo to propose adding a section on this topic.

Thanks for the follow-up!
