### ISSUE TITLE
The footnotes in the main text of the footnote plugin should be numbered and decoupled from the order of footnote writing.

### ISSUE THREAD

**Issue by jiaopengzi** [bent10/marked-extensions#26]
Here's a simple footnote,[^1] and here's a longer one.[^bignote]

[^bignote]: Here's one with multiple paragraphs and code.

    Indent paragraphs to include them in the footnote.

    `{ my code }`

    Add as many paragraphs as you like.

[^1]: This is the first footnote.

---
github markdown Source code
![image](https://github.com/bent10/marked-extensions/assets/52224629/0e17ee53-12da-4bd3-933f-4aa738337003)

Content parsed by github
![image](https://github.com/bent10/marked-extensions/assets/52224629/2114d1ab-7dc4-4148-9384-1639e2ee4f51)

Content parsed by your plugin
![image](https://github.com/bent10/marked-extensions/assets/52224629/b3185b99-3e27-488f-b19a-9dd0dae667bf)

## bug
```
Extension Name: marked-footnote
Extension Version: v1.1.3
```

Seeing your plugin is excellent, I've identified the following two issues.

- Please consider the above footnotes. On GitHub, the superscript in the main text for footnote markers should not display the content of the footnote but rather the sequential number of the footnote in the entire document.

- The writing of footnotes should not be constrained by their position before or after the main text. It should be decoupled to avoid the need to constantly check if the footnote order is correct.

I would greatly appreciate it if you could address these two points. Thank you very much.

**Comment by bent10** [comment]
@jiaopengzi Thank you for bringing these issues to my attention. Really appreciate it!

I have released [v1.2.0](https://github.com/bent10/marked-extensions/releases/tag/marked-footnote%401.2.0) to address this issue.
