### ISSUE TITLE
marked-directive - ESM browser module support

### ISSUE THREAD

**Issue by smurfier** [bent10/marked-extensions#35]
- Extension Name: marked-directive
- Extension Version: 1.0.4

### Use case
Need to be able to use in a browser without npm. Not everyone is using Node and npm to build small use case apps.

### Proposal
Please make a build that supports ems browser module import.

**Comment by bent10** [comment]
We already [have it](https://www.jsdelivr.com/package/npm/marked-directive?tab=files), and you can use `https://cdn.jsdelivr.net/npm/marked-directive/+esm`. Take a look at [this example](https://untitled-zniiqipcb1b2.runkit.sh/).
